### ISSUE TITLE
YAML parser: accept syntax with no newline for mapping-in-a-sequence

### ISSUE THREAD

**Issue by psanan** [sciath/sciath#142]
Currently we have to do this
```
tests:
  - 
    name: foo
    type: exit_code
```
but it's common to want to write
```
tests:
  - name: foo
    type: exit_code
```
The custom YAML (subset) parser could be improved to allow this.
