### ISSUE TITLE
Collect environment variables in YAML input file

### ISSUE THREAD

**Issue by psanan** [sciath/sciath#145]
In some situations a user may want more flexibility in defining their input file, by allowing parameters to be passed.

Motivating example: StagBL:
In basic usage, when an applications's executable is in a predictable place, one can specify commands to execute relative to the YAML input file. However, StagBL uses PETSc's model and allows multiple parallel builds in directories named with a `STAGBL_ARCH` values (which is inherited from a `PETSC_ARCH` value). Thus, the location of the executable to run for a test depends on which build one is interested in, and thus it'd be convenient to specify e.g.

```
environment:
    - STAGBL_DIR
    - STAGBL_ARCH
tests:
    -
         name: test1
         command: $STAGBL_DIR/$STAGBL_ARCH/bin/run -args
         expected: test1.expected
```

Propose to print which variables were collected, and their values. Prefer throwing an error if expected variables are not found (expecting the user to define them as empty, if they intend them to be used that way).
