### ISSUE TITLE
User-defined substitutions

### ISSUE THREAD

**Issue by psanan** [sciath/sciath#155]
Typical test-definition files will have a great deal of repetition.

Some users might like to be able to define subsititutions, e.g. something like

```
definitions:
    MAIN_PROGRAM: ./application --default-parameters-file=HERE/../input.dat --verbose
tests:
    - name: test1
    - command: MAIN_PROGRAM --foo=bar
```

This should be thought about carefully, though, to make sure users get expected behavior with respect to recursively-defined definitions etc. At a minimum, as in the example above, thing like `HERE` and captured environment variables should be expanded.
