### ISSUE TITLE
Harness: test groups

### ISSUE THREAD

**Issue by psanan** [sciath/sciath#32]
Define and report on both automatic and user (tag-based) test groups, and allow them to be quickly included or excluded from the command line and the `Harness` API

**Comment by psanan** [comment]
@dmay23 For this, I propose that in the input file you have either a `group:` or `groups:` key, e.g.
```
tests:
    -
         name: foo
         command: echo foo
         group: smoke
    - 
         name: bar
         command: echo bar
         groups:
             - smoke
             - extra_tests      
    -
         name: foo
         command: echo foo
```

You'd use it by specifying groups to exclude and/or groups to include (exclude all other groups). If you specify both, you'd only run tests in groups that are explicitly included and not explicitly excluded. e.g.
```
python -m sciath -i input.yml                                                                           # run all groups 
python -m sciath -i input.yml  --exclude-groups B                                        # run all groups but B
python -m sciath -i input.yml --include-groups A,B                                      # run groups A and B
python -m sciath -i input.yml --include-groups A,B --exclude-groups  B   # only run group A
````

What do you think about the interface? Short alternatives for the options? I'm thinking `-g` to include groups and `-x` to exclude them.
