### ISSUE TITLE
YAML: add top-level tests: field

### ISSUE THREAD

**Issue by psanan** [sciath/sciath#93]
This would allow us to add settings later. 

An immediate concern is that the current approach to specifying paths relative to the input file itself is to find/replace a hard-coded `HERE`, which could of course clash with the user's commands. The very safest thing to do would be to force them to specify it in the input file, 
e.g.
```
tests:
    -
      name: test1
      command: HERE/../my_executable -input_file HERE/test_files/input.dat
here_marker: HERE
```
